apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "lagoon-logging.fullname" . }}
  labels:
    {{- include "lagoon-logging.labels" . | nindent 4 }}
spec:
  fluentd:
    security:
      podSecurityContext:
        runAsUser: 100
        fsGroup: 0
    scaling:
      replicas: {{ .Values.fluentdReplicaCount }}
  {{- if .Values.fluentbitPrivileged }}
  fluentbit:
    security:
      securityContext:
        privileged: true
  {{- else }}
  fluentbit: {}
  {{- end }}
  controlNamespace: {{ .Release.Namespace | quote }}
