{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.ui.fullname" . }}
  labels:
    {{- include "lagoon-core.ui.labels" . | nindent 4 }}
spec:
{{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lagoon-core.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/api.secret: {{ include (print $.Template.BasePath "/api.secret.yaml") . | sha256sum }}
        checksum/api-db.secret: {{ include (print $.Template.BasePath "/api-db.secret.yaml") . | sha256sum }}
        checksum/keycloak.secret: {{ include (print $.Template.BasePath "/keycloak.secret.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (coalesce .Values.ui.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: ui
        securityContext:
          {{- toYaml .Values.ui.securityContext | nindent 10 }}
        image: "{{ .Values.ui.image.repository }}:{{ coalesce .Values.ui.image.tag .Values.imageTag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        env:
        - name: GRAPHQL_API
          {{- if .Values.lagoonAPIURL }}
          value: {{ .Values.lagoonAPIURL | quote }}
          {{- else }}
          value: https://{{ index .Values.api.ingress.hosts 0 "host" }}/graphql
          {{- end }}
        - name: KEYCLOAK_API
          {{- if .Values.keycloakAPIURL }}
          value: {{ .Values.keycloakAPIURL | quote }}
          {{- else }}
          value: https://{{ index .Values.keycloak.ingress.hosts 0 "host" }}/auth
          {{- end }}
        - name: LAGOON_VERSION
          value: {{ .Chart.AppVersion | replace "-" "." }}
        ports:
        - name: http-3000
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http-3000
        readinessProbe:
          httpGet:
            path: /
            port: http-3000
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
      {{- if .Values.insecureHostMount.services }}
        volumeMounts:
        - name: ui-src
          mountPath: /app/services/ui/src
        - name: ui-env-defaults
          mountPath: /app/services/ui/.env.defaults
        - name: ui-env-schema
          mountPath: /app/services/ui/.env.schema
        - name: ui-package-json
          mountPath: /app/services/ui/package.json
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.insecureHostMount.services }}
      volumes:
      - name: ui-src
        hostPath:
          path: /lagoon/services/ui/src
          type: Directory
      - name: ui-env-defaults
        hostPath:
          path: /lagoon/services/ui/.env.defaults
          type: File
      - name: ui-env-schema
        hostPath:
          path: /lagoon/services/ui/.env.schema
          type: File
      - name: ui-package-json
        hostPath:
          path: /lagoon/services/ui/package.json
          type: File
      {{- end }}
{{- end }}